# coding: utf-8

"""
    certascale API

    Certascale API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.notification_list import NotificationList  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationList(unittest.TestCase):
    """NotificationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationList(self):
        """Test NotificationList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.notification_list.NotificationList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
