# coding: utf-8

"""
    certascale API

    Certascale API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_api import AccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.account_api.AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_create(self):
        """Test case for account_create

        """
        pass

    def test_account_delete(self):
        """Test case for account_delete

        """
        pass

    def test_account_get(self):
        """Test case for account_get

        """
        pass

    def test_account_list(self):
        """Test case for account_list

        """
        pass

    def test_account_update(self):
        """Test case for account_update

        """
        pass

    def test_apikey_create(self):
        """Test case for apikey_create

        """
        pass

    def test_apikey_delete(self):
        """Test case for apikey_delete

        """
        pass

    def test_apikey_get(self):
        """Test case for apikey_get

        """
        pass

    def test_apikey_list(self):
        """Test case for apikey_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
