# coding: utf-8

"""
    certascale API

    Certascale API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notification_api import NotificationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationApi(unittest.TestCase):
    """NotificationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.notification_api.NotificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_notification_acknowledge(self):
        """Test case for notification_acknowledge

        """
        pass

    def test_notification_get(self):
        """Test case for notification_get

        """
        pass

    def test_notification_list(self):
        """Test case for notification_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
