# coding: utf-8

"""
    certascale API

    Certascale API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.domain_api import DomainApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDomainApi(unittest.TestCase):
    """DomainApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.domain_api.DomainApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_certificate_create(self):
        """Test case for certificate_create

        """
        pass

    def test_certificate_delete(self):
        """Test case for certificate_delete

        """
        pass

    def test_certificate_get(self):
        """Test case for certificate_get

        """
        pass

    def test_certificate_list(self):
        """Test case for certificate_list

        """
        pass

    def test_domain_create(self):
        """Test case for domain_create

        """
        pass

    def test_domain_delete(self):
        """Test case for domain_delete

        """
        pass

    def test_domain_get(self):
        """Test case for domain_get

        """
        pass

    def test_domain_list(self):
        """Test case for domain_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
