# coding: utf-8

"""
    certascale API

    Certascale API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.account_definition import AccountDefinition  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountDefinition(unittest.TestCase):
    """AccountDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountDefinition(self):
        """Test AccountDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.account_definition.AccountDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
