# coding: utf-8

"""
    certascale API

    Certascale API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.default_message import DefaultMessage  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultMessage(unittest.TestCase):
    """DefaultMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDefaultMessage(self):
        """Test DefaultMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.default_message.DefaultMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
