---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "certascale API"
  description: "Certascale API documentation"
  license:
    name: "MIT"
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /account:
    get:
      description: "Get the list of accounts (paginated)"
      operationId: "account_list"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
    post:
      description: "Create a new account"
      operationId: "account_create"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/AccountDefinition"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: "#/definitions/AccountDefinition"
            $ref: "#/definitions/PluDefToChange"

  /account/{accountId}:
    parameters:
      - name: "accountId"
        required: true
        in: "path"
        type: "string"
    get:
      description: "Get the details of a specific account"
      operationId: "account_get"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Account doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"
    delete:
      description: "Remove the account"
      operationId: "account_delete"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Account doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"
    put:
      description: "Update an existing account"
      operationId: "account_update"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/PluDefToChange"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Account doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"

  /account/{accountId}/key/:
    parameters:
      - name: "accountId"
        required: true
        in: "path"
        type: "string"
    get:
      description: "Get the list of keys for a given account"
      operationId: "key_get"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Account doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"
    post:
      description: "Create a new key"
      operationId: "key_create"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: "#/definitions/AccountDefinition"
            $ref: "#/definitions/PluDefToChange"


  /account/{accountId}/key/{keyId}:
    parameters:
      - name: "accountId"
        required: true
        in: "path"
        type: "string"
      - name: "keyId"
        required: true
        in: "path"
        type: "string"

    delete:
      description: "Delete a given key"
      operationId: "key_delete"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Account doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"

  /domain:
    get:
      description: "Get the list of your domains"
      operationId: "domain_list"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
    post:
      description: "Register a new domain"
      operationId: "domain_create"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/PluDefToChange"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"

  /domain/{domainName}:
    parameters:
      - name: "domainName"
        required: true
        in: "path"
        type: "string"
    get:
      description: "Get the details of a specific domain"
      operationId: "domain_get"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
    delete:
      description: "Remove the domain"
      operationId: "domain_delete"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
    put:
      description: "Update an existing domain"
      operationId: "domain_update"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/PluDefToChange"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Domain doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"

  /domain/{domainName}/certificate/:
    parameters:
      - name: "domainName"
        in: "path"
        required: true
        type: "string"
    get:
      description: "Get the list of certificate for a specific domain"
      operationId: "certificate_list"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Domain doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"

    post:
      description: "Post an externally generated certificate"
      operationId: "certificate_create"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/PluDefToChange"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Domain doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"

  /domain/{domainName}/certificate/{certificateId}:
    parameters:
      - name: "domainName"
        in: "path"
        required: true
        type: "string"
      - name: "certificateId"
        in: "path"
        required: true
        type: "string"
    get:
      description: "Get a specific certificate and the associated key and CA"
      operationId: "certificate_get"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Certificate or domain doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"


    delete:
      description: "Remove the certificate"
      operationId: "certificate_delete"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Certificate or domain doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"

  /notification:
    get:
      description: "Get all your certificate update notifications"
      operationId: "notification_list"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"

  /notification/{notificationId}:
    parameters:
      - name: "notificationId"
        in: "path"
        required: true
        type: "string"
    get:
      description: "Get specific content for a notification"
      operationId: "notification_get"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Notification doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"
    put:
      description: "Acknowledge the notification"
      operationId: "notification_acknowledge"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/PluDefToChange"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PluDefToChange"
        404:
          description: "Notification doesn't exist"
          schema:
            $ref: "#/definitions/DefaultError"

definitions:
  PluDefToChange:
    type: "object"
    properties:
      id:
        type: "integer"
  DefaultError:
    type: "object"
    properties:
      message:
        type: "string"
  AccountCreateUpdate:
    type: "object"
    properties:
      name:
        type: "string"
      tag:
        properties: {}
  AccountDefinition:
    type: "object"
    properties:
      name:
        type: "string"
      creationDate:
        type: "string"
        format: "date-time"
      ModificationDate:
        type: "string"
        format: "date-time"
      tag:
        properties: {}

