# coding: utf-8

"""
    certascale API

    Certascale API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'secret': 'str',
        'create_date': 'datetime',
        'last_modification_date': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'secret': 'secret',
        'create_date': 'create_date',
        'last_modification_date': 'last_modification_date'
    }

    def __init__(self, id=None, secret=None, create_date=None, last_modification_date=None):  # noqa: E501
        """ApiKey - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._secret = None
        self._create_date = None
        self._last_modification_date = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if secret is not None:
            self.secret = secret
        if create_date is not None:
            self.create_date = create_date
        if last_modification_date is not None:
            self.last_modification_date = last_modification_date

    @property
    def id(self):
        """Gets the id of this ApiKey.  # noqa: E501

        ID of the key  # noqa: E501

        :return: The id of this ApiKey.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiKey.

        ID of the key  # noqa: E501

        :param id: The id of this ApiKey.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def secret(self):
        """Gets the secret of this ApiKey.  # noqa: E501

        key secret (full content at creation, first digits afterward)  # noqa: E501

        :return: The secret of this ApiKey.  # noqa: E501
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this ApiKey.

        key secret (full content at creation, first digits afterward)  # noqa: E501

        :param secret: The secret of this ApiKey.  # noqa: E501
        :type: str
        """

        self._secret = secret

    @property
    def create_date(self):
        """Gets the create_date of this ApiKey.  # noqa: E501


        :return: The create_date of this ApiKey.  # noqa: E501
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this ApiKey.


        :param create_date: The create_date of this ApiKey.  # noqa: E501
        :type: datetime
        """

        self._create_date = create_date

    @property
    def last_modification_date(self):
        """Gets the last_modification_date of this ApiKey.  # noqa: E501


        :return: The last_modification_date of this ApiKey.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modification_date

    @last_modification_date.setter
    def last_modification_date(self, last_modification_date):
        """Sets the last_modification_date of this ApiKey.


        :param last_modification_date: The last_modification_date of this ApiKey.  # noqa: E501
        :type: datetime
        """

        self._last_modification_date = last_modification_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
