# coding: utf-8

"""
    certascale API

    Certascale API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.notification import Notification  # noqa: F401,E501


class NotificationList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'list': 'list[Notification]',
        'next_id': 'int'
    }

    attribute_map = {
        'list': 'list',
        'next_id': 'next_id'
    }

    def __init__(self, list=None, next_id=None):  # noqa: E501
        """NotificationList - a model defined in Swagger"""  # noqa: E501

        self._list = None
        self._next_id = None
        self.discriminator = None

        if list is not None:
            self.list = list
        if next_id is not None:
            self.next_id = next_id

    @property
    def list(self):
        """Gets the list of this NotificationList.  # noqa: E501


        :return: The list of this NotificationList.  # noqa: E501
        :rtype: list[Notification]
        """
        return self._list

    @list.setter
    def list(self, list):
        """Sets the list of this NotificationList.


        :param list: The list of this NotificationList.  # noqa: E501
        :type: list[Notification]
        """

        self._list = list

    @property
    def next_id(self):
        """Gets the next_id of this NotificationList.  # noqa: E501


        :return: The next_id of this NotificationList.  # noqa: E501
        :rtype: int
        """
        return self._next_id

    @next_id.setter
    def next_id(self, next_id):
        """Sets the next_id of this NotificationList.


        :param next_id: The next_id of this NotificationList.  # noqa: E501
        :type: int
        """

        self._next_id = next_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotificationList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
