# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.api_key import ApiKey  # noqa: F401,E501
from swagger_server import util


class ApiKeyList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, list: List[ApiKey]=None, next_id: int=None):  # noqa: E501
        """ApiKeyList - a model defined in Swagger

        :param list: The list of this ApiKeyList.  # noqa: E501
        :type list: List[ApiKey]
        :param next_id: The next_id of this ApiKeyList.  # noqa: E501
        :type next_id: int
        """
        self.swagger_types = {
            'list': List[ApiKey],
            'next_id': int
        }

        self.attribute_map = {
            'list': 'list',
            'next_id': 'next_id'
        }

        self._list = list
        self._next_id = next_id

    @classmethod
    def from_dict(cls, dikt) -> 'ApiKeyList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiKeyList of this ApiKeyList.  # noqa: E501
        :rtype: ApiKeyList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list(self) -> List[ApiKey]:
        """Gets the list of this ApiKeyList.


        :return: The list of this ApiKeyList.
        :rtype: List[ApiKey]
        """
        return self._list

    @list.setter
    def list(self, list: List[ApiKey]):
        """Sets the list of this ApiKeyList.


        :param list: The list of this ApiKeyList.
        :type list: List[ApiKey]
        """

        self._list = list

    @property
    def next_id(self) -> int:
        """Gets the next_id of this ApiKeyList.


        :return: The next_id of this ApiKeyList.
        :rtype: int
        """
        return self._next_id

    @next_id.setter
    def next_id(self, next_id: int):
        """Sets the next_id of this ApiKeyList.


        :param next_id: The next_id of this ApiKeyList.
        :type next_id: int
        """

        self._next_id = next_id
