# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DomainCreateUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, tag: object=None):  # noqa: E501
        """DomainCreateUpdate - a model defined in Swagger

        :param name: The name of this DomainCreateUpdate.  # noqa: E501
        :type name: str
        :param tag: The tag of this DomainCreateUpdate.  # noqa: E501
        :type tag: object
        """
        self.swagger_types = {
            'name': str,
            'tag': object
        }

        self.attribute_map = {
            'name': 'name',
            'tag': 'tag'
        }

        self._name = name
        self._tag = tag

    @classmethod
    def from_dict(cls, dikt) -> 'DomainCreateUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DomainCreateUpdate of this DomainCreateUpdate.  # noqa: E501
        :rtype: DomainCreateUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this DomainCreateUpdate.


        :return: The name of this DomainCreateUpdate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DomainCreateUpdate.


        :param name: The name of this DomainCreateUpdate.
        :type name: str
        """

        self._name = name

    @property
    def tag(self) -> object:
        """Gets the tag of this DomainCreateUpdate.


        :return: The tag of this DomainCreateUpdate.
        :rtype: object
        """
        return self._tag

    @tag.setter
    def tag(self, tag: object):
        """Sets the tag of this DomainCreateUpdate.


        :param tag: The tag of this DomainCreateUpdate.
        :type tag: object
        """

        self._tag = tag
